CREATE TABLE public.sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    items JSONB NOT NULL,
    pending_approval JSONB,
    revision BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT sessions_id_positive CHECK (id > 0),
    CONSTRAINT sessions_revision_nonnegative CHECK (revision >= 0),
    CONSTRAINT sessions_items_array CHECK (jsonb_typeof(items) = 'array'),
    CONSTRAINT sessions_pending_object CHECK (
        pending_approval IS NULL
        OR jsonb_typeof(pending_approval) = 'object'
    )
);
